pipeline:
  env-info:
    image: alpine:3.6
    commands:
    - whoami
    - env

  fs-info:
    image: alpine:3.6
    commands:
    - ls -la ./
    - ls -la ${HOME}
    - ls -la /
    - mount
    - df -h

  mem-info:
    image: alpine:3.6
    commands:
    - free -m
    - >
      for stat in memory.limit_in_bytes memory.max_usage_in_bytes ; do \
        echo -n "$stat:    " ; \
        cat /sys/fs/cgroup/memory/$stat ; \
      done
