pipeline:
  env-info:
    image: alpine:3.6
    commands:
    - whoami
    - env | sort

  fs-info:
    image: alpine:3.6
    commands:
    # echo true on failure to prevent premature exit of build
    - ls -la ./ || true
    - ls -la ${HOME} || true
    - ls -la / || true
    - mount
    - df -h

  mem-info:
    image: alpine:3.6
    commands:
    - free -m
    - >
      for stat in memory.limit_in_bytes memory.max_usage_in_bytes ; do \
        echo -n "$stat:    " ; \
        cat /sys/fs/cgroup/memory/$stat ; \
      done
